#spring:
#  application:
#    name: hostel
#  datasource:
#    url: jdbc:postgresql://localhost:5432/hostel
#    username: postgres
#    password: 123
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
spring:
  application:
    name: hostel

  datasource:
    url: jdbc:mysql://localhost:3306/hostel?useSSL=false&serverTimezone=UTC
    username: root
    password: 123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  profiles:
    active: test

app:
  path:
    v1: api.v1

server:
  port: 8080   # Browser မှာသုံးချင်တဲ့ port

