spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hostel
    username: postgres
    password: 123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

app:
  data:
    access-life: 50
    refresh-life: 300          
      

